# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Task',
        ),
    ]
