# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_list',
            field=models.TextField(default=''),
        ),
    ]
